### ISSUE TITLE
Great mod, one suggestion.

### ISSUE THREAD

**Issue by madmangenius5** [ReadOnlyDevelopment/SpaceCraftX-Reloaded#1]
I would like to see this mod available for a mod like Space-Bosstools which is a revamp of galacticraft, but for 1.16.5. If it is possible to make a version that uses Space-Bosstools, I would definitely download it.

**Comment by ROMVoid95** [comment]
It is not. Space Boss Tools is not a revamp of Galacticraft, its a mod inspired by Galacticraft, and a 1.16+ Galacticraft is under development. 

I do not plan to ever create a version for SpaceBossTools, even if I entertained the idea, that mod is a mccreator mod so there would be many license conflicts and there is no deobf/api provided.
